# Generated by Django 4.1.1 on 2022-09-15 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_home_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='Trending_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='home',
            name='Trending_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='home',
            name='newshoes_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='home',
            name='newshoes_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='picture',
            field=models.ImageField(null=True, upload_to='picture/'),
        ),
        migrations.AddField(
            model_name='home',
            name='sale_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='home',
            name='sale_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='shoename',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='home',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
