# Generated by Django 4.1.1 on 2022-09-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_home_trending_picture_home_newshoes_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_name', models.CharField(blank=True, max_length=50)),
                ('sale_price', models.IntegerField(blank=True, null=True)),
                ('sale_picture', models.ImageField(null=True, upload_to='sale/')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newshoes_name', models.CharField(blank=True, max_length=50)),
                ('newshoes_price', models.IntegerField(blank=True, null=True)),
                ('newshoes_picture', models.ImageField(null=True, upload_to='new/')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='trending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trending_name', models.CharField(blank=True, max_length=100)),
                ('Trending_price', models.IntegerField(blank=True, null=True)),
                ('Trending_picture', models.ImageField(null=True, upload_to='trending/')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='home',
            name='Trending_name',
        ),
        migrations.RemoveField(
            model_name='home',
            name='Trending_picture',
        ),
        migrations.RemoveField(
            model_name='home',
            name='Trending_price',
        ),
        migrations.RemoveField(
            model_name='home',
            name='newshoes_name',
        ),
        migrations.RemoveField(
            model_name='home',
            name='newshoes_picture',
        ),
        migrations.RemoveField(
            model_name='home',
            name='newshoes_price',
        ),
        migrations.RemoveField(
            model_name='home',
            name='sale_name',
        ),
        migrations.RemoveField(
            model_name='home',
            name='sale_picture',
        ),
        migrations.RemoveField(
            model_name='home',
            name='sale_price',
        ),
        migrations.RemoveField(
            model_name='home',
            name='updated',
        ),
    ]
